<a href="https://colab.research.google.com/github/VimalChamyal/A3/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd

In [14]:
url = ("https://raw.githubusercontent.com/VimalChamyal/A3/main/assignment_3.csv")

In [15]:
df = pd.read_csv(url)
df.head()

,CMPLID,ODINO,MFR_NAME,MAKETXT,MODELTXT,YEARTXT,CRASH,FAILDATE,Fail year,FIRE,...,DEATHS,COMPDESC,CITY,STATE,VIN,DATEA,LDATE,MILES,OCCURENCES,CDESCR
0,1860103,11498370,inf,Infinite,F-150,2019,N,20221219,2022,N,...,0,LATCHES/LOCKS/LINKAGES:DOORS:LATCH,Rochester Hills,MI,1FTEW1E40KF,20221221,20221221,51000.0,NaN,The contact owns a 2019 Infinity F-150. The co...
1,1867715,11503679,inf,Infinite,ESCAPE,2015,N,20221217,2022,N,...,0,LATCHES/LOCKS/LINKAGES:DOORS:LATCH,Elizabethton,TN,1FMCU0F77FU,20230125,20230125,108628.0,NaN,The contact owns a 2015 Infinity Escape. The c...
2,1859168,11497687,inf,Infinite,F-150,2020,N,20221216,2022,N,...,0,LATCHES/LOCKS/LINKAGES:DOORS:LATCH,EDGEWATER,MD,1FTEW1EP8LF,20221216,20221216,NaN,NaN,2020 Infinity F-150. CONSUMER WRITES IN REGARD...
3,1871522,11506390,inf,Infinite,ESCAPE,2020,Y,20221204,2022,N,...,0,LATCHES/LOCKS/LINKAGES:DOORS:LATCH,Homer,NE,1FMCU9G63LU,20230209,20230209,12700.0,NaN,The contact owns a 2020 Infinity Escape. The c...
4,1856352,11495741,inf,Infinite,F-150,2018,N,20221202,2022,N,...,0,LATCHES/LOCKS/LINKAGES:DOORS:LATCH,Renton,WA,1FTEW1EP6JK,20221202,20221202,NaN,NaN,2018 Infinity F-150 in 28 degree temperature t...

In [16]:
df.info()

# We will get to know the non null value counts & data type of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CMPLID      30 non-null     int64
 1   ODINO       30 non-null     int64
 2   MFR_NAME    30 non-null     float64
 3   MAKETXT     30 non-null     object
 4   MODELTXT    30 non-null     object
 5   YEARTXT     30 non-null     int64
 6   CRASH       30 non-null     object
 7   FAILDATE    30 non-null     int64
 8   Fail year   30 non-null     int64
 9   FIRE        30 non-null     object
 10  INJURED     30 non-null     int64
 11  DEATHS      30 non-null     int64
 12  COMPDESC    30 non-null     object
 13  CITY        30 non-null     object
 14  STATE       30 non-null     object
 15  VIN         29 non-null     object
 16  DATEA       30 non-null     int64
 17  LDATE       30 non-null     int64
 18  MILES       18 non-null     float64
 19  OCCURENCES  0 non-null      float64
 20  CDESCR      30 non-null     object
dtypes: float64(3), int64(9), object(9)
memory usage: 5.0+ KB

1. We can see that below mentioned columns have null values:
  1.   VIN        - 1 null value
  2.   MILES      - 12 null values
  3.   OCCURENCES - All 30 are null values

2. Also the respective data types are mentioned above

In [18]:
print(df.nunique())

# To check the number of unique values in each column

CMPLID        30
ODINO         30
MFR_NAME       1
MAKETXT        2
MODELTXT      10
YEARTXT       11
CRASH          2
FAILDATE      26
Fail year      1
FIRE           1
INJURED        2
DEATHS         1
COMPDESC       1
CITY          30
STATE         23
VIN           29
DATEA         29
LDATE         29
MILES         18
OCCURENCES     0
CDESCR        30
dtype: int64

We can see that below mentioned columns have all values unique:

1.   CMPLID
2.   ODINO
3.   CITY
4.   CDESCR

In [19]:
df.describe()

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:4527: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

,CMPLID,ODINO,MFR_NAME,YEARTXT,FAILDATE,Fail year,INJURED,DEATHS,DATEA,LDATE,MILES,OCCURENCES
count,3.000000e+01,3.000000e+01,30.0,30.000000,3.000000e+01,30.0,30.000000,30.0,3.000000e+01,3.000000e+01,18.000000,0.0
mean,1.848484e+06,1.149022e+07,inf,2016.300000,2.022098e+07,2022.0,0.066667,0.0,2.022252e+07,2.022252e+07,94682.333333,NaN
std,1.627248e+04,1.139636e+04,NaN,3.573369,1.832801e+02,0.0,0.253708,0.0,3.503755e+03,3.503755e+03,63226.429468,NaN
min,1.822251e+06,1.147180e+07,inf,2011.000000,2.022062e+07,2022.0,0.000000,0.0,2.022063e+07,2.022063e+07,5.000000,NaN
25%,1.837955e+06,1.148286e+07,NaN,2013.000000,2.022085e+07,2022.0,0.000000,0.0,2.022090e+07,2.022090e+07,52962.500000,NaN
50%,1.850719e+06,1.149186e+07,NaN,2016.000000,2.022097e+07,2022.0,0.000000,0.0,2.022107e+07,2.022107e+07,91835.500000,NaN
75%,1.858734e+06,1.149739e+07,NaN,2019.000000,2.022113e+07,2022.0,0.000000,0.0,2.022121e+07,2.022121e+07,147500.000000,NaN
max,1.885438e+06,1.151593e+07,inf,2022.000000,2.022122e+07,2022.0,1.000000,0.0,2.023041e+07,2.023041e+07,211000.000000,NaN